# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qlLklcwzaVXyI8h0riG-ygLbJHuSOMNQ
"""

# app.py
# app.py
import streamlit as st
import pandas as pd

# ==== Aturan JRA ====
JRA_RULES = [
    {"label": "JRA 1994", "start": 1994, "end": 2001, "excel": 1994},
    {"label": "JRA 2002", "start": 2002, "end": 2005, "excel": 2002},
    {"label": "JRA 2006", "start": 2006, "end": 2018, "excel": 2006},
    {"label": "JRA 2019", "start": 2019, "end": 2026, "excel": 2019},
]

def get_jra_info(year: int):
    for rule in JRA_RULES:
        if rule["start"] <= year <= rule["end"]:
            return rule
    return None

def cari_kode(tahun: int, judul: str, df: pd.DataFrame):
    jra_info = get_jra_info(tahun)
    if not jra_info:
        return f"Tidak ada JRA untuk tahun {tahun}"

    jra_label = jra_info["label"]
    excel_jra = jra_info["excel"]

    # Bersihkan df
    df = df[['Jenis Dokumen', 'JRA', 'Kode']].copy()
    df = df.dropna(subset=['JRA'])
    df["JRA"] = df["JRA"].astype('Int64')

    df_filtered = df[df["JRA"] == excel_jra]

    if df_filtered.empty:
        return f"Tidak ada data untuk JRA {excel_jra} di Excel."

    for _, row in df_filtered.iterrows():
        if judul.lower() in str(row["Jenis Dokumen"]).lower():
            return f"JRA: {jra_label}, Kode Arsip: {row['Kode']}"

    return f"Tidak ditemukan kode untuk judul '{judul}' pada JRA {jra_label}"

# ==== Streamlit UI ====
st.set_page_config(page_title="Pencari Kode Arsip (JRA)", page_icon="🗂️")
st.title("🔎 Pencarian Kode Arsip")

# Upload atau gunakan default Excel
uploaded = st.file_uploader("Upload knowledge_base.xlsx (opsional)", type=["xlsx"])
if uploaded is not None:
    df = pd.read_excel(uploaded)
else:
    try:
        df = pd.read_excel("knowledge_base.xlsx")
    except Exception:
        st.error("File knowledge_base.xlsx tidak ditemukan.")
        st.stop()

st.header("Input Dokumen")
col1, col2 = st.columns([2,1])
with col1:
    judul = st.text_input("Judul / Deskripsi Dokumen", placeholder="contoh: Penugasan Dinas")
with col2:
    tahun = st.number_input("Tahun Dokumen", min_value=1900, max_value=2100, value=2017, step=1)

if st.button("Cari Kode Arsip"):
    if not judul.strip():
        st.warning("Isi judul dokumen dulu.")
    else:
        hasil = cari_kode(tahun, judul, df)
        st.success(hasil)
